/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope;

// 1. Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// 2. Claim clients immediately so the service worker controls the page on first load
self.skipWaiting();
clientsClaim();

// 2. Handle /share-target POST request
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  if (url.pathname === '/share-target' && event.request.method === 'POST') {
    event.respondWith(
      (async () => {
        try {
          const formData = await event.request.formData();
          const file = formData.get('chat') || Array.from(formData.values()).find((v) => v instanceof File);

          if (file instanceof File) {
            const cache = await caches.open('gita4youth-share-target');
            // Store the file in cache as '/shared-file'
            await cache.put(
              new Request('/shared-file'),
              new Response(file, {
                headers: {
                  'Content-Type': file.type || 'application/octet-stream',
                  'x-filename': encodeURIComponent(file.name),
                },
              })
            );
          }
        } catch (err) {
          console.error('Failed to cache shared file in service worker:', err);
        }

        // Redirect to root with query param
        return Response.redirect('/?share-target=true', 303);
      })()
    );
  }
});
